# Generated by Django 5.1.7 on 2025-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('DOB', models.DateField()),
                ('Aadhar', models.BigIntegerField()),
                ('pan', models.CharField(max_length=10)),
                ('mobile', models.IntegerField()),
                ('address', models.TextField()),
                ('acc', models.BigAutoField(default=1234567890, primary_key=True, serialize=False)),
                ('bal', models.DecimalField(decimal_places=2, default=1000.0, max_digits=7)),
                ('pin', models.IntegerField(default=0)),
            ],
        ),
    ]
