# Generated by Django 5.1.7 on 2025-04-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='karthiknaij1234@gmail.com', max_length=254),
        ),
    ]
